### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by 3kh0** [pixelamp1/pixelamp1.github.io#1]
Hello there!

I have looked through your GitHub repo and found that it was originally mine so I ask you to please take this down to respect my work and what I do. If the original one was blocked then you can contact me and I can give you more links.

Echo

**Comment by pixelamp1** [comment]
I have just deleted the games that I had and you also had, replacing the source code of the games, to just an iframe.

**Comment by 3kh0** [comment]
> I have just deleted the games that I had and you also had, replacing the source code of the games, to just an iframe.

No, you did not even give credit. No iframes. Completely remove them. Did you even ask the owner of these games if you could inclue them to your website?
